// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type AtrCalculation struct {
	ID                   int32        `json:"id"`
	Symbol               string       `json:"symbol"`
	CalculationTimestamp time.Time    `json:"calculation_timestamp"`
	AtrValue             string       `json:"atr_value"`
	CreatedAt            sql.NullTime `json:"created_at"`
}

type CandleDailyBollinger struct {
	ID                int32     `json:"id"`
	Symbol            string    `json:"symbol"`
	CalculationDate   time.Time `json:"calculation_date"`
	TimePeriod        int32     `json:"time_period"`
	AveragePrice      string    `json:"average_price"`
	StandardDeviation string    `json:"standard_deviation"`
	UpperBand         string    `json:"upper_band"`
	LowerBand         string    `json:"lower_band"`
	CurrentPrice      string    `json:"current_price"`
	DeviationFromAvg  string    `json:"deviation_from_avg"`
}

type Candles12h struct {
	ID              int32        `json:"id"`
	Symbol          string       `json:"symbol"`
	CandleTimestamp time.Time    `json:"candle_timestamp"`
	OpenPrice       string       `json:"open_price"`
	HighPrice       string       `json:"high_price"`
	LowPrice        string       `json:"low_price"`
	ClosePrice      string       `json:"close_price"`
	Volume          int64        `json:"volume"`
	CreatedAt       sql.NullTime `json:"created_at"`
}

type CandlesDaily struct {
	ID         int32        `json:"id"`
	Symbol     string       `json:"symbol"`
	CandleDate time.Time    `json:"candle_date"`
	OpenPrice  string       `json:"open_price"`
	HighPrice  string       `json:"high_price"`
	LowPrice   string       `json:"low_price"`
	ClosePrice string       `json:"close_price"`
	Volume     int64        `json:"volume"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type HistoricalBar struct {
	ID                 int32          `json:"id"`
	Symbol             string         `json:"symbol"`
	Timeframe          string         `json:"timeframe"`
	Timestamp          time.Time      `json:"timestamp"`
	OpenPrice          string         `json:"open_price"`
	HighPrice          string         `json:"high_price"`
	LowPrice           string         `json:"low_price"`
	ClosePrice         string         `json:"close_price"`
	Volume             int64          `json:"volume"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	PriceChange        sql.NullString `json:"price_change"`
	PriceChangePercent sql.NullString `json:"price_change_percent"`
}

type NewsArticle struct {
	ID          int32          `json:"id"`
	Symbol      string         `json:"symbol"`
	Headline    string         `json:"headline"`
	Url         string         `json:"url"`
	PublishedAt time.Time      `json:"published_at"`
	Source      sql.NullString `json:"source"`
	Sentiment   sql.NullString `json:"sentiment"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type PortfolioHistory struct {
	ID             int32          `json:"id"`
	TotalEquity    string         `json:"total_equity"`
	CashBalance    string         `json:"cash_balance"`
	PositionsValue string         `json:"positions_value"`
	DayChange      sql.NullString `json:"day_change"`
	TotalReturn    sql.NullString `json:"total_return"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type Position struct {
	ID            int32          `json:"id"`
	Symbol        string         `json:"symbol"`
	Quantity      string         `json:"quantity"`
	AvgEntryPrice string         `json:"avg_entry_price"`
	CurrentPrice  sql.NullString `json:"current_price"`
	MarketValue   sql.NullString `json:"market_value"`
	UnrealizedPnl sql.NullString `json:"unrealized_pnl"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type RsiCalculation struct {
	ID                   int32        `json:"id"`
	Symbol               string       `json:"symbol"`
	CalculationTimestamp time.Time    `json:"calculation_timestamp"`
	RsiValue             string       `json:"rsi_value"`
	CreatedAt            sql.NullTime `json:"created_at"`
}

type ScoutList struct {
	ID           int32          `json:"id"`
	Symbol       string         `json:"symbol"`
	Reason       sql.NullString `json:"reason"`
	AddedAt      sql.NullTime   `json:"added_at"`
	TriggerPrice sql.NullString `json:"trigger_price"`
	TriggerType  sql.NullString `json:"trigger_type"`
	IsActive     sql.NullBool   `json:"is_active"`
	Notes        sql.NullString `json:"notes"`
}

type Signal struct {
	ID           int32          `json:"id"`
	Symbol       string         `json:"symbol"`
	SignalType   string         `json:"signal_type"`
	CurrentPrice string         `json:"current_price"`
	SmaValue     sql.NullString `json:"sma_value"`
	Confidence   sql.NullString `json:"confidence"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	Executed     sql.NullBool   `json:"executed"`
}

type SupportLevel struct {
	ID         int32        `json:"id"`
	Symbol     string       `json:"symbol"`
	LevelPrice string       `json:"level_price"`
	LevelType  string       `json:"level_type"`
	DetectedAt time.Time    `json:"detected_at"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Trade struct {
	ID            int32          `json:"id"`
	SignalID      sql.NullInt32  `json:"signal_id"`
	Symbol        string         `json:"symbol"`
	Side          string         `json:"side"`
	Quantity      string         `json:"quantity"`
	Price         string         `json:"price"`
	TotalValue    string         `json:"total_value"`
	Commission    sql.NullString `json:"commission"`
	AlpacaOrderID sql.NullString `json:"alpaca_order_id"`
	Status        sql.NullString `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	FilledAt      sql.NullTime   `json:"filled_at"`
}

type WhaleAlert struct {
	ID             int32        `json:"id"`
	Symbol         string       `json:"symbol"`
	AlertType      string       `json:"alert_type"`
	Amount         string       `json:"amount"`
	Price          string       `json:"price"`
	AlertTimestamp time.Time    `json:"alert_timestamp"`
	CreatedAt      sql.NullTime `json:"created_at"`
}
